### ISSUE TITLE
Support sparse Hessians and Jacobians

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/ADNLPModels.jl#44]

**Comment by jbcaillau** [comment]
@amontoison @tmigot Thanks for the update on sparse Jacobians. Just tested on some examples from the tutorial + `runtests` from the cloned `main` branch: pass 👍🏽. Going to check what the performance increase with `Ipopt` on optimal control problems 🤞🏾. Knowing that we deal with one step scheme discretisation of ODE's, so that the associated constraints are sparse (and bandwise). Of course, looking forward to testing sparse Hessians too.

J'ai testé (exemple tuto + runtests sur clone branche main) : nickel. On va voir sur nos premiers cas tests si ça bouge les perfs. Sachant qu'on est sur des contraintes non-linéaires provenant de la discrétisation par des méthodes à un pas d'une ODE,
